title: GwangHyeok Yu Blog
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://ifree015.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: light
